[package]
name = "dawproject-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
xml = "0.8.20"
zip = "2.1.3"

